defaults_pg: &defaults_pg
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username:
  password:

test:
  <<: *defaults_pg
  database: calenderby_test

development:
  <<: *defaults_pg
  database: calenderby_development
